default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1
  port: <%= ENV.fetch("TECHPIT_MYSQL_PORT") { 3306 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: file_uploader_app_sample_development

test:
  <<: *default
  database: file_uploader_app_sample_test

production:
  <<: *default
  database: backend_production
  username: backend
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
